### ISSUE TITLE
GraphQL ESLint integration with Typescript ESLint plugins

### ISSUE THREAD

**Issue by ajotaos** [dotansimha/graphql-eslint#241]
I get an error when using my Typescript project already using `@typescript-eslint` when I try introducing the `graphql-eslint` steps from the `README`. This is in response to this request https://github.com/dotansimha/graphql-eslint/issues/215#issuecomment-749126868 @dotansimha 

`package.json`
```json
{
  "name": "graphql-eslint-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "apollo-server": "2.19.0",
    "graphql": "15.4.0"
  },
  "devDependencies": {
    "@graphql-eslint/eslint-plugin": "0.6.0",
    "@tsconfig/node14": "1.0.0",
    "@typescript-eslint/eslint-plugin": "4.11.0",
    "@typescript-eslint/parser": "4.11.0",
    "eslint": "7.16.0",
    "graphql-cli": "4.1.0",
    "graphql-config": "3.2.0",
    "typescript": "4.1.3"
  }
}
```

`tsconfig.json`
```json
{
  "extends": "@tsconfig/node14/tsconfig.json",
  "compilerOptions": {
    "incremental": true,
    "rootDir": "src",
    "outDir": "dist",
    "declaration": true,
    "declarationMap": true,
    "sourceMap": true
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules"]
}
```

`.graphqlrc.yml`
```yml
---
schema: ./src/type-defs.ts
documents: null
```

`.eslintrc.yml`
```yml
---
root: true
env:
  es2020: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 11
  sourceType: module
  project: ./tsconfig.json
plugins:
  - '@typescript-eslint'
rules: {}
overrides:
  - files:
      - '*.tsx'
      - '*.ts'
      - '*.jsx'
      - '*.js'
    processor: '@graphql-eslint/graphql'
  - files:
      - '*.graphql'
    parser: '@graphql-eslint/eslint-plugin'
    plugins:
      - '@graphql-eslint'
    rules: {}
```

And the schema file `src/type-defs.ts`
<img width="1212" alt="Screen Shot 2020-12-21 at 3 44 09 PM" src="https://user-images.githubusercontent.com/51857835/102820516-62211e80-43a3-11eb-9965-2c5f56014688.png">
